eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gamelogic-server

server:
  port: 8086

quizServerName: http://localhost:8083
playerServerName: http://localhost:8081
roundServerName: http://localhost:8085
