version: '3.3'

services:

  postgres-category:
    image: "postgres:10"

  postgres-subcategory:
    image: "postgres:10"

  eureka:
      build:
        context: ./eureka
        dockerfile: Dockerfile
      ports:
        - "8761:8761"

  subcategory-module:
    build:
      context: ./subcategory
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - eureka
      - postgres-subcategory
      - category-module

  category-module:
    build:
      context: ./category
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - eureka
      - postgres-category

  