version: '3.3'

services:

  postgres-user:
    image: "postgres:10"
  postgres-category:
    image: "postgres:10"

  postgres-subcategory:
    image: "postgres:10"

  postgres-quiz:
    image: "postgres:10"

  postgres-player:
    image: "postgres:10"

  postgres-round:
    image: "postgres:10"

  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:3"

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"

  subcategory-server:
    build:
      context: ./subcategory
      dockerfile: Dockerfile
#    ports:
#      - "8082:8080"
    depends_on:
      - eureka
      - postgres-subcategory
      - category-server

  category-server:
    build:
      context: ./category
      dockerfile: Dockerfile
#    ports:
#      - "8084:8080"
    depends_on:
      - eureka
      - postgres-category

  category-server-2:
    build:
      context: ./category
      dockerfile: Dockerfile
#    ports:
#      - "8084:8080"
    depends_on:
      - eureka
      - postgres-category

  quiz-server:
    build:
      context: ./quiz
      dockerfile: Dockerfile
#    ports:
#      - "8083:8080"
    depends_on:
      - eureka
      - postgres-quiz
      - subcategory-server
  player-server:
    build:
      context: ./player
      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
    depends_on:
      - eureka
      - rabbitmq
      - redis

  round-server:
    build:
      context: ./round
      dockerfile: Dockerfile
#    ports:
#      - "8085:8080"
    depends_on:
      - eureka
      - postgres-round
      - rabbitmq

  gamelogic-server:
    build:
      context: ./gamelogic
      dockerfile: Dockerfile
#    ports:
#      - "8086:8080"
    depends_on:
      - eureka
      - rabbitmq
      - redis
      - player-server
      - round-server
      - quiz-server
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - redis
      - eureka
      - postgres-user
      - gamelogic-server
      - player-server
      - quiz-server
      - round-server