version: '3.3'

services:

  postgres-category:
    image: "postgres:10"
#    ports:
#      - "5432:5432"
  postgres-subcategory:
      image: "postgres:10"

  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:3"

#  eureka:
#    build:
#      context: ./eureka
#      dockerfile: Dockerfile
  #   ports:
  #     - "8761:8761"

  category-module:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres-category
#      - eureka

  subcategory-module:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8082:8080"
    depends_on:
      - postgres-subcategory
#      - eureka
      - category-server