version: '3.3'

services:

  postgres-category:
    image: "postgres:10"

  postgres-subcategory:
    image: "postgres:10"

  category-module:
    build:
      context: ./category
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres-category

  subcategory-module:
    build:
      context: ./subcategory
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres-subcategory
      - category-module