
zuul:
  routes:
    player:
      path: /players/**
    quiz:
      path: /quizzes/**
    subcategory:
      path: /subcategories/**
    category:
      path: /categories/**
    round:
      path: /rounds/**
    gamelogic:
      path: /play/**


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
  contextPath: /api/v1