version: '3.3'

services:

  postgres-category:
    image: "postgres:10"
    ports:
      - "5432:5432"

  category-module:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres-category