eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: round-server
  rabbitmq:
    host: rabbitmq
  datasource:
    url: "jdbc:postgresql://postgres-round:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
server:
  port: 8080